### ISSUE TITLE
jq dependency automatic install

### ISSUE THREAD

**Issue by tevosouza** [giggio/speedtest#2]
@giggio,
What are your thoughts about jq dependency auto-install, would it include unnecessary complexity?? 
```
jq 1.5 is in the official Debian and Ubuntu repositories. Install using sudo apt-get install jq.

jq 1.5 is in the official Fedora repository. Install using sudo dnf install jq.

jq 1.4 is in the official openSUSE repository. Install using sudo zypper install jq.

jq 1.5 is in the official Arch repository. Install using sudo pacman -S jq.
``` 
I'm thinking it because jq installation is different based on the distro and it maybe gives some issues to us

**Comment by giggio** [comment]
This is made to run in a container, I don't see a problem.
